# Generated by Django 5.2.6 on 2025-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Autor do livro', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_description',
            field=models.TextField(blank=True, help_text='Descrição do autor do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(help_text='Categoria do livro', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do livro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, help_text='Imagem do livro', null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Status do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN do livro', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, help_text='Idioma do livro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_edition',
            field=models.IntegerField(blank=True, help_text='Última edição do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Número de páginas do livro', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do livro', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Editora do livro', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo do livro', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Título do livro', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data de atualização do livro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, help_text='Ano de publicação do livro', null=True),
        ),
    ]
